# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MarcheALOmbre
                                 A QGIS plugin
 This plugin calculates for a given hike the shady and sunny parts
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-11
        copyright            : (C) 2025 by Yolanda Seifert
        email                : yolanda.seifert@gmx.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Yolanda Seifert'
__date__ = '2025-12-11'
__copyright__ = '(C) 2025 by Yolanda Seifert'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MarcheALOmbre class from file MarcheALOmbre.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .marche_a_lombre import MarcheALOmbrePlugin
    return MarcheALOmbrePlugin()
